//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPRSGxZ.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Amplifiers : global::System.Configuration.ApplicationSettingsBase {
        
        private static Amplifiers defaultInstance = ((Amplifiers)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Amplifiers())));
        
        public static Amplifiers Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Master</string>
  <string>Slave 1</string>
  <string>Slave 2</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Name {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Name"]));
            }
            set {
                this["Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfInt xmlns:xsi=\"http://www.w3.org" +
            "/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <int>" +
            "6</int>\r\n  <int>6</int>\r\n  <int>6</int>\r\n</ArrayOfInt>")]
        public int[] ZoneCount {
            get {
                return ((int[])(this["ZoneCount"]));
            }
            set {
                this["ZoneCount"] = value;
            }
        }
    }
}
