//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPRSGxZ.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Zones : global::System.Configuration.ApplicationSettingsBase {
        
        private static Zones defaultInstance = ((Zones)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Zones())));
        
        public static Zones Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Zone 1</string>
  <string>Zone 2</string>
  <string>Zone 3</string>
  <string>Zone 4</string>
  <string>Zone 5</string>
  <string>Zone 6</string>
  <string>Zone 7</string>
  <string>Zone 8</string>
  <string>Zone 9</string>
  <string>Zone 10</string>
  <string>Zone 11</string>
  <string>Zone 12</string>
  <string>Zone 13</string>
  <string>Zone 14</string>
  <string>Zone 15</string>
  <string>Zone 16</string>
  <string>Zone 17</string>
  <string>Zone 18</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Name {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Name"]));
            }
            set {
                this["Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfBoolean xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <boolean>false</boolean>
  <boolean>false</boolean>
  <boolean>false</boolean>
  <boolean>false</boolean>
  <boolean>false</boolean>
  <boolean>false</boolean>
  <boolean>false</boolean>
  <boolean>false</boolean>
  <boolean>false</boolean>
  <boolean>false</boolean>
  <boolean>false</boolean>
  <boolean>false</boolean>
  <boolean>false</boolean>
  <boolean>false</boolean>
  <boolean>false</boolean>
  <boolean>false</boolean>
  <boolean>false</boolean>
  <boolean>false</boolean>
</ArrayOfBoolean>")]
        public bool[] Enabled {
            get {
                return ((bool[])(this["Enabled"]));
            }
            set {
                this["Enabled"] = value;
            }
        }
    }
}
